Hw5 done
ok-technopolis-2021/Bakin_Daniil pull request #7
Opened 2021-12-08 23:05 UTC by donebd

2021-12-13 15:49 UTC, BusinessDuck requested changes

2021-12-13 15:49 UTC, BusinessDuck commented on gulpfile.js
> +    {
в целом можно обьединить их в одно приложение, и используя iife сборку также начать использовать import в JS файлах. Тк все это одно приложение, оно и тему переклчюать умеет и скилы добавлять. То есть на странице с добавлением скилов в теории тоже можно переключить тему тк это все та же визитка

пример настройки роллап:
```
export default {
  input: 'src/main.js',
  output: [
    {
      file: 'app.js',
      format: 'iife'
    }
  ],
  plugins: [json()]
};
```

2021-12-13 15:49 UTC, BusinessDuck commented on src/scripts/skills.js
> +    skills;
это в целом не обязательно писать, сработает и так

2021-12-13 15:49 UTC, BusinessDuck commented on src/scripts/skills.js
> +    //could be set in constructor
ага

2021-12-13 15:49 UTC, BusinessDuck commented on src/scripts/skills.js
> +                `<div class="skill">
вставка точно безопасная? Мы же обсуждали XSS уязвимости

2021-12-13 15:49 UTC, BusinessDuck commented on src/scripts/skills.js
> +        this.redrawSkills()
Реализация хорошая, только перерисовываем мы каждый раз полностью все, может попробовать подсрезать углы? Хотябы на добавление нового если его еще нет - ставить его в конец, а вот более сложные случаи лучше уже очищать. В этой задаче должна стать понятной боль синхронизации элементов и их состояния в модели, это на нативном JS не удобно делать так, чтобы и код был красивый и грамотный и синхронизция была без танцев с бубном. Angular это решил одним из первых, он назвал это two-way data-binding, когда магическим образом данные из модели синхронизивались с view.

2021-12-13 15:49 UTC, BusinessDuck commented on src/scripts/skills.js
> +        this.redrawSkills()
И раздели пожалуйста файлы JS на составные файлы, пример настройки сборки я привел, если что приходи в Direct.

2021-12-15 19:11 UTC, donebd commented
Разделил файлики, пофиксил инъекцию, сделал redraw конкретного skill'а при добавлении и удалении (хотя я не уверен что при удалении из середины он сам все не перерисовывает).

2021-12-18 12:51 UTC, BusinessDuck approved these changes
Очень годно, молодец!

Что понравилось
1) Разделение на файлы и импорты, но почитай про export default и простой export, какие плюсы и минусы у этого и когда что лучше использовать. Лично я вообще не сторонник export default использовать
2) Визуальный стиль хороший
3) Код локаничный и сбалансированный
4) Использование форм и обработка горячих клавиш благодаря этому

Что не понравилось
1) Пути в файле после сборки ошибочные для скриптов и стилей, это не заведется на веб сервере, нужно было `./styles.css` , а не `./dist/..что-то-там./styles.css`
2) Не хватает ширины полям ввода, они как-то мелко посажены и иконкиудаления немного пляшут не оцентравно

----
Итого 37/40

2022-01-04 17:14 UTC, merged